title: Risk Investigator
email: tu-email@example.com
description: 'Explora mi blog para encontrar artículos y reflexiones sobre finanzas, contabilidad, riesgo financiero, bienes raíces y mucho más.'
baseurl: '/mi-sitio-web'
url: 'https://patr1c10jr.github.io'
theme: minima
